# -*- coding: utf-8 -*-
"""Mcmurray_extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13QhAWnw2oUi7UdZT4Eg5tEQ_Jj6v2cdf
"""

!pip install pymupdf
!pip install pypdf
!pip install orjsonl

import fitz
import re
import orjsonl

text = ""
textbook = fitz.open('textbook1.pdf')

def ParseProblem(problemtext) :
  out = problemtext
  actualText = re.split("\n.*\n.*\nAccess for free at openstax.org", out)
  out = ""
  for text in actualText :
    out += text
  actualText = re.split("\n[1-9][0-9]* •.*\n.*", out)
  out = ""
  for text in actualText :
    out += text
  actualText = re.split("\nAnswer Key\n.*", out)
  out = ""
  for text in actualText :
    out += text
  actualText = re.split("\nChapter.*", out)
  out = ""
  for text in actualText :
    out += text
  return out

def findProblems(alltext) :
  out = []
  chapters = re.split("(\nCHAPTER|\nAPPENDIX|\nINDEX)", alltext)
  for chapter in chapters :
    subchapters = re.split("[1-9][0-9]*\\.[1-9][0-9]*.*", chapter)
    for subchapter in subchapters :
      problems = re.split("PROBLEM", subchapter)
      for problem in range(1, len(problems)) :
        out.append(ParseProblem(problems[problem]))
  return out

for page in textbook :
  text += page.get_text()

problemsText = re.split("\nANSWER KEY.*\nChapter 1", text)[0]
solutionsText = re.split("\nANSWER KEY.*\nChapter 1", text)[1]

allProblems = findProblems(problemsText)
allSolutions = findProblems(solutionsText)

questions = {}
questionsJSON = []

for problem in allProblems :
  id = re.search("\n[1-9][0-9]*-[1-9][0-9]*", problem)
  if id != None :
    problem = problem[id.end() + 1:]
    id = id.group(0)
    id = id[1:]
    questions[id] = [problem]

for solution in allSolutions :
  id = re.search("\n[1-9][0-9]*-[1-9][0-9]*", solution)
  if id != None :
    solution = solution[id.end() + 1:]
    id = id.group(0)
    id = id[1:]
    if id in questions :
      questions[id].append(solution)
    # else :
    #   questions[id] = [None, solution]

for id in questions :
  if len(questions[id]) == 2 and questions[id][1] != '':
    questionsJSON.append({
        # "id" : id,
        "prompt" : questions[id][0],
        "completion" : questions[id][1]
    })
  # else :
  #   questionsJSON.append({
  #       "id" : id,
  #       "prompt" : questions[id][0],
  #       "completion" : None
  #   })

for JSON in questionsJSON :
  print(JSON)

orjsonl.save('prompts_completions_no_empty.jsonl', questionsJSON)