# -*- coding: utf-8 -*-
"""Textbook_QA_Extractor_Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qd4gxG0EMhd2K1paUtnZZk7vdp74OWwg
"""

#Install necessary packages if running in Google Colab
!pip install pymupdf
!pip install pypdf
!pip install orjsonl

#Working With .pdf and .txt Documents
from pypdf import PdfReader
import re
import fitz

#Handling JSONL Objects
import orjsonl

class arraysToJSONL :

  def __init__(self, problemsArray, solutionsArray, spacer="-") :
    self.questions = {}
    for problem in problemsArray :
      id = self.re.search("[1-9][0-9]*" + spacer + "[1-9][0-9]*", problem)
      if id != None :
        problem = problem[id.end() + 1:]
        id = id.group(0)
        self.questions[id] = [problem]
    for solution in solutionsArray :
      id = self.re.search("[1-9][0-9]*" + spacer + "[1-9][0-9]*", solution)
      if id != None :
        solution = solution[id.end() + 1:]
        id = id.group(0)
        if id in self.questions :
          self.questions[id].append(solution)
    self.JSONarray = self.__getJSONL()

  def __getJSONL(self) :
    out = []
    for id in self.questions :
      if len(self.questions[id]) == 2 and self.questions[id][0] != '' and self.questions[id][1] != '' :
        JSON = {
            "prompt" : self.questions[id][0],
            "completion" : self.questions[id][1]
        }
        out.append(JSON)
    return out

  def saveJSONL(self, filename) :
    self.orjsonl.save(filename, self.JSONarray)

  def showJSONL(self) :
    for JSON in self.JSONarray :
      print(JSON)

# Create .txt document
from pypdf import PdfReader

text = ""

reader = PdfReader('textbook.pdf')

for page in reader.pages :
  page_text = page.extract_text()
  text += page_text

with open("textbook.txt", "w") as myfile :
  myfile.write(text)

# Removes the header of each page
from pypdf import PdfReader
import re

text = ""

reader = PdfReader('textbook.pdf')

for page in reader.pages :
  all_page_text = page.extract_text()
  page_text_index = re.search(".*", all_page_text)
  page_text = all_page_text[page_text_index.end():]
  text += page_text

with open("textbook.txt", "w") as myfile :
  myfile.write(text)

# Find the problems section and solutions sections and save them to text document.
# Manually open the text and place markers before running this code.
# MARKERS: @----PROBLEMS START----@
#          @----PROBLEMS END----@
#          @----SOLUTIONS START----@
#          @----SOLUTIONS END----@
import re

myfile = open("textbookmarked.txt", "r")
text = myfile.read()

def findTextBetweenMarkers(text, marker="PROBLEMS") :
  out = ""
  sections = []
  firstSplitArray = re.split("@----" + marker + " START----@", text)
  for upperSection in firstSplitArray :
    section = re.split("@----" + marker + " END----@", upperSection)
    if len(section) != 1 :
      sections.append(section[0])
  for section in sections :
    out += section
  return out

problemsText = findTextBetweenMarkers(text = text, marker = "PROBLEMS")
solutionsText = findTextBetweenMarkers(text = text, marker = "SOLUTIONS")

with open("problems.txt", "w") as myfile :
  myfile.write(problemsText)

with open("solutions.txt", "w") as myfile :
  myfile.write(solutionsText)

import re

problemsFile = open("problems.txt", "r")
solutionsFile = open("solutions.txt", "r")
problemsText = problemsFile.read()
solutionsText = solutionsFile.read()

problemsArray = re.split("PROBLEM", problemsText)
solutionsArray = re.split("SOL", solutionsText)

JSONL = arraysToJSONL(problemsArray = problemsArray, solutionsArray = solutionsArray, spacer = "\\.")

JSONL.showJSONL()
JSONL.saveJSONL("levine_prompt_completion.jsonl")

# TEST CODE.... OTHER PDF LOADER...

from pypdf import PdfReader

reader = PdfReader('textbook1.pdf')

page = reader.pages[18]

print(page.extract_text())

import fitz
import re
import orjsonl

text = ""
textbook = fitz.open('textbook1.pdf')

def ParseProblem(problemtext) :
  out = problemtext
  actualText = re.split("\n.*\n.*\nAccess for free at openstax.org", out)
  out = ""
  for text in actualText :
    out += text
  actualText = re.split("\n[1-9][0-9]* •.*\n.*", out)
  out = ""
  for text in actualText :
    out += text
  actualText = re.split("\nAnswer Key\n.*", out)
  out = ""
  for text in actualText :
    out += text
  actualText = re.split("\nChapter.*", out)
  out = ""
  for text in actualText :
    out += text
  return out

def findProblems(alltext) :
  out = []
  chapters = re.split("(\nCHAPTER|\nAPPENDIX|\nINDEX)", alltext)
  for chapter in chapters :
    subchapters = re.split("[1-9][0-9]*\\.[1-9][0-9]*.*", chapter)
    for subchapter in subchapters :
      problems = re.split("PROBLEM", subchapter)
      for problem in range(1, len(problems)) :
        out.append(ParseProblem(problems[problem]))
  return out

for page in textbook :
  text += page.get_text()

problemsText = re.split("\nANSWER KEY.*\nChapter 1", text)[0]
solutionsText = re.split("\nANSWER KEY.*\nChapter 1", text)[1]

allProblems = findProblems(problemsText)
allSolutions = findProblems(solutionsText)

questions = {}
questionsJSON = []

for problem in allProblems :
  id = re.search("\n[1-9][0-9]*-[1-9][0-9]*", problem)
  if id != None :
    problem = problem[id.end() + 1:]
    id = id.group(0)
    id = id[1:]
    questions[id] = [problem]

for solution in allSolutions :
  id = re.search("\n[1-9][0-9]*-[1-9][0-9]*", solution)
  if id != None :
    solution = solution[id.end() + 1:]
    id = id.group(0)
    id = id[1:]
    if id in questions :
      questions[id].append(solution)
    # else :
    #   questions[id] = [None, solution]

for id in questions :
  if len(questions[id]) == 2 and questions[id][1] != '':
    questionsJSON.append({
        # "id" : id,
        "prompt" : questions[id][0],
        "completion" : questions[id][1]
    })
  # else :
  #   questionsJSON.append({
  #       "id" : id,
  #       "prompt" : questions[id][0],
  #       "completion" : None
  #   })

for JSON in questionsJSON :
  print(JSON)

orjsonl.save('prompts_completions_no_empty.jsonl', questionsJSON)

import re

myfile = open("textbook2.txt", "r")
text = myfile.read()

def findProblems(alltext) :
  out = []
  chapters = re.split("(\nChapter.*|\nThis page intentionally left blank)", alltext)
  for chapter in chapters :
    problemsec = re.split("\nProblems", chapter)
    if len(problemsec) > 1 :
      problemsec = problemsec[-1]
      out.append(problemsec)
  return out

problemsText = re.split("\nAnswers to Selected Problems", text)[0]

x = findProblems(problemsText)
print(x[30])
# print(x[0])
# print(problemsText)